Implement first version of vgc::topology, vgc::workspace; Use workspace in Canvas and app (#992)
vgc/vgc pull request #1089
Opened 2023-01-17 17:44 UTC by PixelRick

#992

2023-01-17 18:00 UTC, PixelRick commented
Current bugs:
- crash related to elementsOutOfSync_ on update after doing some undo/redo.

2023-01-20 12:32 UTC, dalboris requested changes

2023-01-20 12:32 UTC, dalboris commented on libs/vgc/workspace/workspace.h
> +class VGC_WORKSPACE_API Workspace : public core::Object {
Add comment: "This implementation is still preliminary and the API may change significantly"

2023-01-20 12:32 UTC, dalboris commented on libs/vgc/workspace/workspace.h
> +    VacElement* vgcElement_;
Add comment: "this is the root element"

2023-01-20 12:32 UTC, dalboris commented on libs/vgc/workspace/workspace.cpp
> +class ScopedRecursiveBoolGuard {
Add comment explaining the purpose of this.

2023-01-20 20:28 UTC, dalboris approved these changes

2023-01-20 20:28 UTC, merged

2023-02-09 15:05 UTC, PixelRick commented
Related issue: #1107